//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Shared.Properties {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
          "Infra.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CourierHasOrderAlready {
            get {
                return ResourceManager.GetString("CourierHasOrderAlready", resourceCulture);
            }
        }
        
        public static string DeliveryRequestNotExists {
            get {
                return ResourceManager.GetString("DeliveryRequestNotExists", resourceCulture);
            }
        }
        
        public static string DuplicateRequest {
            get {
                return ResourceManager.GetString("DuplicateRequest", resourceCulture);
            }
        }
        
        public static string Resources_en {
            get {
                return ResourceManager.GetString("Resources_en", resourceCulture);
            }
        }
        
        public static string Resources_fa {
            get {
                return ResourceManager.GetString("Resources_fa", resourceCulture);
            }
        }
        
        public static string InvalidClearPrice {
            get {
                return ResourceManager.GetString("InvalidClearPrice", resourceCulture);
            }
        }
        
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        public static string InvalidOrderId {
            get {
                return ResourceManager.GetString("InvalidOrderId", resourceCulture);
            }
        }
        
        public static string InvalidSecretCode {
            get {
                return ResourceManager.GetString("InvalidSecretCode", resourceCulture);
            }
        }
        
        public static string InvalidSellCount {
            get {
                return ResourceManager.GetString("InvalidSellCount", resourceCulture);
            }
        }
        
        public static string InvalidSmsCode {
            get {
                return ResourceManager.GetString("InvalidSmsCode", resourceCulture);
            }
        }
        
        public static string NotAllowedTorequestDelivery {
            get {
                return ResourceManager.GetString("NotAllowedTorequestDelivery", resourceCulture);
            }
        }
        
        public static string OrderIsAssignedToDelivery {
            get {
                return ResourceManager.GetString("OrderIsAssignedToDelivery", resourceCulture);
            }
        }
        
        public static string TransporterAlreadyExists {
            get {
                return ResourceManager.GetString("TransporterAlreadyExists", resourceCulture);
            }
        }
        
        public static string TransporterShouldBeAccepted {
            get {
                return ResourceManager.GetString("TransporterShouldBeAccepted", resourceCulture);
            }
        }
        
        public static string TransporterShouldBeRegistered {
            get {
                return ResourceManager.GetString("TransporterShouldBeRegistered", resourceCulture);
            }
        }
        
        public static string UNEXPECTED_RESULT {
            get {
                return ResourceManager.GetString("UNEXPECTED_RESULT", resourceCulture);
            }
        }
        
        public static string UNSUPPORTED_MIME_TYPE_SPECIFIED {
            get {
                return ResourceManager.GetString("UNSUPPORTED_MIME_TYPE_SPECIFIED", resourceCulture);
            }
        }
        
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        public static string DataAlreadyExisits {
            get {
                return ResourceManager.GetString("DataAlreadyExisits", resourceCulture);
            }
        }
        
        public static string ImageTypeIsRequired {
            get {
                return ResourceManager.GetString("ImageTypeIsRequired", resourceCulture);
            }
        }
        
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        public static string InvalidCaptcha {
            get {
                return ResourceManager.GetString("InvalidCaptcha", resourceCulture);
            }
        }

        public static string ServiceNotInitialized {
            get {
                return ResourceManager.GetString("ServiceNotInitialized", resourceCulture);
            }
        }
    }
}
